name: cve-bin-tool

on: [push, pull_request]

jobs:
  check:
    name: Black check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jpetrucciani/black-check@master

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
         os: [ubuntu-latest]
         python: [3.6, 3.7]
    env:
      ACTIONS: 1
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Make cache dir
      run: |
        pwd
        mkdir .cache
        mkdir .cache/cve-bin-tool/
        touch .cache/cve-bin-tool/nvd.vulnerabilities.db
    - name: Run tests
      run: |
        python -m unittest test.test_scanner
    - name: Check files
      run: |
        ls -al ~/.cache/
        ls -al ~/.cache/cve-bin-tool/

