name: cve-bin-tool

on: [push, pull_request]

jobs:
  black_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with black
      run: |
        pip install black
        black --check cve_bin_tool/
        black --check test/

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
         os: [ubuntu-latest, windows-latest]
         python: [2.7, 3.6, 3.7]
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        ACTIONS=1 python setup.py test
