name: cve-bin-tool

on: [push, pull_request]

jobs:
  check:
    name: Black check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jpetrucciani/black-check@master

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
         os: [ubuntu-latest, windows-latest]
         python: [3.6, 3.7]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        ACTIONS=1 python setup.py test

